import { Campaign } from '../app/pages/campaign/interfaces/campaign.interface';
export const campaignsData: Campaign[] = [
    {
        id: 1,
        name: 'Adidas Sport Hat',
        category: ['fashion', 'travel'],
        budget: 100,
        coverImg: 'assets/img/demo/product08-01.jpg',
        platform: ['instagram', 'youtube'],
        placement: ['feed', 'story'],
        requirement: 'test',
        caption: 'aa',
        locationtags: ['washington'],
        tags: ['adidas'],
        tags2: ['fashion', 'sports'],
        ages: [30, 60],
        followers: [2000, 4500],
        periodStart: '09/02/2020',
        periodEnd: '09/09/2020',
        gallery: ['assets/img/demo/product08-02.jpg', 'assets/img/demo/product08-03.jpg', '', '', ''],
        gender: 'male',
        city: '',
        country: '',
        quests: [1],
        contents: [2],
        langs: ['en'],
        billingName: '',
        billingAddress1: '',
        billingAddress2: '',
        billingState: '',
        billingCity: '',
        billingZipcode: '',
        description: 'Cancellation due to simple change of mind or change of destination after delivery is not allowed.',
        favorite: false,
    },
    {
        id: 2,
        name: 'Nike Running Shoes',
        category: ['fashion', 'travel', 'sports'],
        budget: 100,
        coverImg: 'assets/img/demo/product07-01.jpg',
        platform: ['instagram', 'facebook'],
        placement: ['feed', 'story'],
        requirement: 'test',
        caption: 'adf',
        tags: ['nike'],
        tags2: ['fashion'],
        ages: [30, 60],
        followers: [2000, 4500],
        periodStart: '09/02/2020',
        periodEnd: '09/09/2020',
        gallery: ['assets/img/demo/product07-02.jpg', 'assets/img/demo/product07-03.jpg', 'assets/img/demo/product07-04.jpg', '', ''],
        gender: 'male',
        city: '',
        country: '',
        quests: [1],
        contents: [2],
        langs: ['en'],
        billingName: '',
        billingAddress1: '',
        billingAddress2: '',
        billingState: '',
        billingCity: '',
        billingZipcode: '',
        description: 'Showing face, Picture wearing  a product',
        favorite: true,
    },
    // {
    //     id: 3,
    //     name: 'Nike Women Tank Top',
    //     category: ['fashion', 'travel', 'sports', 'food'],
    //     budget: 100,
    //     coverImg: 'assets/img/demo/product10-01.jpg',
    //     platform: ['facebook', 'youtube'],
    //     placement: ['feed', 'story'],
    //     requirement: 'test',
    //     caption: '',
    //     tags: ['nike'],
    //     tags2: ['fashion'],
    //     ages: [30, 60],
    //     followers: [2000, 4500],
    //     periodStart: '09/02/2020',
    //     periodEnd: '09/09/2020',
    //     gallery: ['assets/img/demo/product10-02.jpg', 'assets/img/demo/product10-03.jpg', 'assets/img/demo/product10-04.jpg', '', ''],
    //     gender: 'male',
    //     city: '',
    //     country: '',
    //     quests: [1],
    //     contents: [2],
    //     langs: ['en'],
    //     billingName: '',
    //     billingAddress1: '',
    //     billingAddress2: '',
    //     billingState: '',
    //     billingCity: '',
    //     billingZipcode: '',
    //     description: 'Showing face, Picture wearing  a product',
    //     favorite: false,
    // },
    // {
    //     id: 4,
    //     name: 'Wireless Earphone',
    //     category: ['travel', 'sports'],
    //     budget: 100,
    //     coverImg: 'assets/img/demo/product09-01.jpg',
    //     platform: ['facebook', 'youtube'],
    //     placement: ['feed', 'story'],
    //     requirement: 'test',
    //     caption: '',
    //     tags: ['nike'],
    //     tags2: ['fashion'],
    //     ages: [30, 60],
    //     followers: [2000, 4500],
    //     periodStart: '09/02/2020',
    //     periodEnd: '09/09/2020',
    //     gallery: ['assets/img/demo/product09-02.jpg', 'assets/img/demo/product09-03.jpg', 'assets/img/demo/product09-04.jpg', '', ''],
    //     gender: 'male',
    //     city: '',
    //     country: '',
    //     quests: [1],
    //     contents: [2],
    //     langs: ['en'],
    //     billingName: '',
    //     billingAddress1: '',
    //     billingAddress2: '',
    //     billingState: '',
    //     billingCity: '',
    //     billingZipcode: '',
    //     description: 'Showing face, Picture wearing  a product',
    //     favorite: false,
    // },
    // {
    //     id: 5,
    //     name: 'Sport Sunglasses',
    //     category: ['travel', 'sports', 'fashion'],
    //     budget: 100,
    //     coverImg: 'assets/img/demo/product11-01.jpg',
    //     platform: ['instagram', 'facebook'],
    //     placement: ['feed', 'story'],
    //     requirement: 'test',
    //     caption: '',
    //     tags: ['nike'],
    //     tags2: ['fashion'],
    //     ages: [30, 60],
    //     followers: [2000, 4500],
    //     periodStart: '09/02/2020',
    //     periodEnd: '09/09/2020',
    //     gallery: ['assets/img/demo/product11-02.jpg', 'assets/img/demo/product11-03.jpg', '', '', ''],
    //     gender: 'male',
    //     city: '',
    //     country: '',
    //     quests: [1],
    //     contents: [2],
    //     langs: ['en'],
    //     billingName: '',
    //     billingAddress1: '',
    //     billingAddress2: '',
    //     billingState: '',
    //     billingCity: '',
    //     billingZipcode: '',
    //     description: 'Showing face, Picture wearing  a product',
    //     favorite: false,
    // },
    // {
    //     id: 6,
    //     name: 'Sport Bag',
    //     category: ['travel', 'sports', 'fashion'],
    //     budget: 100,
    //     coverImg: 'assets/img/demo/product12-01.jpg',
    //     platform: ['instagram', 'facebook'],
    //     placement: ['feed', 'story'],
    //     requirement: 'test',
    //     caption: '',
    //     tags: ['nike'],
    //     tags2: ['fashion'],
    //     ages: [30, 60],
    //     followers: [2000, 4500],
    //     periodStart: '09/02/2020',
    //     periodEnd: '09/09/2020',
    //     gallery: ['assets/img/demo/product12-02.jpg', 'assets/img/demo/product12-03.jpg', 'assets/img/demo/product12-04.jpg', '', ''],
    //     gender: 'male',
    //     city: '',
    //     country: '',
    //     quests: [1],
    //     contents: [2],
    //     langs: ['en'],
    //     billingName: '',
    //     billingAddress1: '',
    //     billingAddress2: '',
    //     billingState: '',
    //     billingCity: '',
    //     billingZipcode: '',
    //     description: 'Showing face, Picture wearing  a product',
    //     favorite: false,
    // }
]
