import { Category } from '../app/pages/campaign/interfaces/category.interface';
export const categoriesData: Category[] = [
    { value: 'art', label: 'Art'},
    { value: 'baby', label: 'Baby'},
    { value: 'beauty', label: 'Beauty'},
    { value: 'book', label: 'Book'},
    { value: 'clothing', label: 'clothing'},
    { value: 'collectible', label: 'collectible'},
    { value: 'electronic', label: 'Electronic'},    
    { value: 'entertainment', label: 'Entertainment'},
    { value: 'fashion', label: 'Fashion'}, 
    { value: 'fitness', label: 'Fitness'},
    { value: 'food', label: 'Food'},
    { value: 'health', label: 'Health'},    
    { value: 'home', label: 'Home Appliance'},    
    { value: 'jewelry', label: 'Jewelry'},
    { value: 'market', label: 'Marketplace'},
    { value: 'music', label: 'Music'},
    { value: 'outdoor', label: 'Outdoor'},
    { value: 'pet', label: 'Pet supply'},
    { value: 'software', label: 'Software'},
    { value: 'technology', label: 'Technology'},
    { value: 'toy', label: 'Toy'},
    { value: 'travel', label: 'Travel'},
    { value: 'vehicle', label: 'Vehicle'},
    { value: 'other', label: 'Others'}
];
export const profCatsData: Category[] = [
    { value: 'art', label: 'Art'},
    { value: 'baby', label: 'Baby'},
    { value: 'beauty', label: 'Beauty'},
    { value: 'book', label: 'Book'},
    { value: 'clothing', label: 'clothing'},
    { value: 'collectible', label: 'collectible'},
    { value: 'electronic', label: 'Electronic'},    
    { value: 'entertainment', label: 'Entertainment'},
    { value: 'fashion', label: 'Fashion'}, 
    { value: 'fitness', label: 'Fitness'},
    { value: 'food', label: 'Food'},
    { value: 'health', label: 'Health'},    
    { value: 'home', label: 'Home Appliance'},    
    { value: 'jewelry', label: 'Jewelry'},
    { value: 'market', label: 'Marketplace'},
    { value: 'music', label: 'Music'},
    { value: 'outdoor', label: 'Outdoor'},
    { value: 'pet', label: 'Pet supply'},
    { value: 'software', label: 'Software'},
    { value: 'technology', label: 'Technology'},
    { value: 'toy', label: 'Toy'},
    { value: 'travel', label: 'Travel'},
    { value: 'vehicle', label: 'Vehicle'},
    { value: 'other', label: 'Others'},
]
